defaults:
  - data_paths: default
  - map_config: vlmaps
  - params: default
  - _self_
nav:
  valid_range: 1
  vis: False
  tasks_per_scene: 20
scene_id: 0
output: ${data_paths.home}/code/vlmaps/data/mapdata

# indexing params
decay_rate: 0.01
index_2d: True
init_categories: True
regions: True
# REGULAR = 0,
# POSTPROCESSED = 1,
# INSTANCES = 2,
# PREDICTED = 3,
# VLMAP_INSTANCES = 4,
# OUR_INSTANCES = 5,
# PREDICTED_POSTPROCESSED = 6,
type: 2