defaults:
  - data_paths: default
  - map_config: vlmaps
  - params: default
  - _self_
nav:
  valid_range: 1
  vis: False
  tasks_per_scene: 20
scene_id: 0
output: "${data_paths.home}/code/vlmaps/data/mapdata"

# indexing params
decay_rate: 0.01
index_2d: True
init_categories: True
regions: True
# REGULAR = 0,
# POSTPROCESSED = 1,
# INSTANCES = 2,
# PREDICTED = 3,
# VLMAP_INSTANCES = 4,
# OUR_INSTANCES = 5,
# PREDICTED_POSTPROCESSED = 6,
ask_for_type: False
type: 1
ask_for_color: False
# 0: rgb
# 1: semantic
# 2: regions
# 3: instances
color: 1
filter: False
ask_for_filter: False
filter_label: 27
classes: "${data_paths.home}/code/vlmaps/cfg/mpcat40_edit.tsv"
delimiter: ;
direct_path: True
#direct_path_path: "${data_paths.home}/Desktop/vlmaps/Jmby2/vlmaps-lseg.h5df"
direct_path_path: "${data_paths.home}/Desktop/vlmaps/Jmby2/vlmaps-openseg.h5df"
